Marcar Asistencias/Controllers/AusenciasController.cs
using Marcar_Asistencias.Models;
using Marcar_Asistencias.Repositories;
using Marcar_Asistencias.Services.Email;
using Microsoft.AspNetCore.Mvc;
using proyectometodologias.models;

namespace Marcar_Asistencias.Controllers
{
    public class AusenciasController : Controller
    {
        private readonly IAusenciasRepository _ausenciasRepository;
        private readonly IEmailService _emailService;

        public AusenciasController(IAusenciasRepository ausenciasRepository, IEmailService emailService)
        {
            _ausenciasRepository = ausenciasRepository;
            _emailService = emailService;
        }

        public ActionResult Index()
        {
            var ausencias = _ausenciasRepository.GetAll();
            return View(ausencias);
        }

        public ActionResult Details(int id)
        {
            var ausencia = _ausenciasRepository.GetById(id);
            if (ausencia == null)
            {
                return NotFound();
            }
            return View(ausencia);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AusenciasModels ausencia)
        {
            try
            {
                _ausenciasRepository.Add(ausencia);
                TempData["message"] = "Datos guardados con éxito";

                string email = "HeladosSarita@gmail.com";
                string subject = "Nuevo asunto de ausencias";
                string type = "Ausencia";
                _emailService.SendEmail(email, $"Tu pedido de ausencia ha sido registrado con éxito por: {ausencia.TipoAusencia}", subject, type);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return View(ausencia);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var ausencia = _ausenciasRepository.GetById(id);
            if (ausencia == null)
            {
                return NotFound();
            }
            return View(ausencia);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, AusenciasModels ausencia)
        {
            if (id != ausencia.IDAusencias)
            {
                return BadRequest();
            }

            try
            {
                var existingAusencia = _ausenciasRepository.GetById(id);
                if (existingAusencia == null)
                {
                    return NotFound();
                }

                _ausenciasRepository.Edit(ausencia);
                TempData["editAusencias"] = "Se editó con éxito";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return View(ausencia);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var ausencia = _ausenciasRepository.GetById(id);
            if (ausencia == null)
            {
                return NotFound();
            }
            return View(ausencia);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, AusenciasModels ausencia)
        {
            try
            {
                var existingAusencia = _ausenciasRepository.GetById(id);
                if (existingAusencia == null)
                {
                    return NotFound();
                }

                _ausenciasRepository.Delete(id);
                TempData["deleteAusencias"] = "Se eliminó la ausencia con éxito";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["deleteAusencia"] = ex.Message;
                return View(ausencia);
            }
        }
    }
}

Marcar Asistencias/Controllers/ComentariosController.cs
using Marcar_Asistencias.Models;
using Marcar_Asistencias.Repositories;
using Marcar_Asistencias.Services.Email;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NuGet.DependencyResolver;

namespace Marcar_Asistencias.Controllers
{
    public class ComentariosController : Controller
    {

        private readonly IComentariosRepository _comentariosRepository;
		private readonly IEmailService _emailService;

		public ComentariosController(IComentariosRepository comentariosRepository, IEmailService emailService)
        {
            _comentariosRepository = comentariosRepository;
            _emailService = emailService;
        }

        public ActionResult Index()
        {
            return View(_comentariosRepository.GetAll());
        }

       
        public ActionResult Details(int id)
        {
            return View();
        }

        
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ComentariosModel comentarios)
        {
            try
            {
                _comentariosRepository.Add(comentarios);

				TempData["message"] = "Datos guardados con exito";

				string email = "developers@help.sv.com";
				string subject = comentarios.Tipo;
				string type = "Comment";
				_emailService.SendEmail(email, comentarios.Texto, subject, type);

				return RedirectToAction(nameof(Index));
			}
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;

                return View(comentarios);
            }
        }

        
        public ActionResult Edit(int id)
        {
            var comentarios = _comentariosRepository.GetById(id);

            if (comentarios == null)
            {
                return NotFound();
            }

			string email = "developers@help.sv.com";
			string subject = comentarios.Tipo;
			string type = "Comment";
			_emailService.SendEmail(email, comentarios.Texto, subject, type);

			return View(comentarios);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ComentariosModel comentarios)
        {
            try
            {
                _comentariosRepository.Edit(comentarios);

                TempData["editComentario"] = "Se editó el comentario.";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(comentarios);
            }
        }

        
        public ActionResult Delete(int id)
        {

            var comentarios = _comentariosRepository.GetById(id);

            if (comentarios == null)
            {
                return NotFound();
            }

            return View(comentarios);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(ComentariosModel comentarios)
        {
            try
            {
                _comentariosRepository.Delete(comentarios.ComentarioNotaID);

                TempData["deleteComentario"] = "Se eliminó el comentario con éxito";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["deleteComment"] = ex.Message;

                return View(comentarios);
            }
        }
    }
}

Marcar Asistencias/Controllers/EmpleadosController.cs
using Marcar_Asistencias.Repositories;
using Marcar_Asistencias.Services.Email;
using Microsoft.AspNetCore.Mvc;
using proyectometodologias.models;

namespace Marcar_Asistencias.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly IEmpleadosRepository _empleadosRepository;
        private readonly IEmailService _emailService;

        public EmpleadosController(IEmpleadosRepository empleadosRepository, IEmailService emailService)
        {
            _empleadosRepository = empleadosRepository;
            _emailService = emailService;
        }

        public ActionResult Index()
        {
            return View(_empleadosRepository.GetAll());
        }

        public ActionResult Details(int id)
        {
            var empleado = _empleadosRepository.GetById(id);
            if (empleado == null)
            {
                return NotFound();
            }
            return View(empleado);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmpleadosModel empleados)
        {
            if (!ModelState.IsValid)
            {
                return View(empleados);
            }

            try
            {
                _empleadosRepository.Add(empleados);
                TempData["message"] = "Datos guardados con éxito";

                string email = "HeladosSarita@gmail.com";
                string subject = "Nuevo empleado Sarita";
                string type = "Empleado";
                _emailService.SendEmail(email, $"El empleado {empleados.Nombre} ha sido registrado con éxito.", subject, type);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["message"] = ex.Message;
                return View(empleados);
            }
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var empleados = _empleadosRepository.GetById(id);

            if (empleados == null)
            {
                return NotFound();
            }

            return View(empleados);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(EmpleadosModel empleados)
        {
            try
            {
                _empleadosRepository.Edit(empleados);
                TempData["editEmpleado"] = "Se editó el empleado con éxito";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["editEmpleado"] = ex.Message;
                return View(empleados);
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var empleados = _empleadosRepository.GetById(id);

            if (empleados == null)
            {
                return NotFound();
            }

            return View(empleados);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteEmplo(int id)
        {
            try
            {
                var existingEmpleado = _empleadosRepository.GetById(id);
                if (existingEmpleado == null)
                {
                    return NotFound();
                }

                _empleadosRepository.Delete(id);
                TempData["deleteEmpleado"] = "Se eliminó el empleado con éxito";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["deleteEmpleado"] = ex.Message;
                return RedirectToAction(nameof(Delete), new { id });
            }
        }
    }
}

Marcar Asistencias/Controllers/VacacionesController.cs
using Marcar_Asistencias.Models;
using Marcar_Asistencias.Repositories;
using Marcar_Asistencias.Services.Email;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Marcar_Asistencias.Controllers
{
    public class VacacionesController : Controller
    {

        private readonly IVacacionesRepository _vacacionesRepository;
		private readonly IEmailService _emailService;

		public VacacionesController(IVacacionesRepository vacacionesRepository, IEmailService emailService)
        {
            _vacacionesRepository = vacacionesRepository;
			_emailService = emailService;
		}

        public ActionResult Index()
        {
            return View(_vacacionesRepository.GetAll());
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VacacionesModel vacaciones)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _vacacionesRepository.Add(vacaciones);

                    TempData["message"] = "Datos guardados con éxito";

                    string email = "empleado@empleado.com";
                    string subject = vacaciones.Tipo;
                    string type = "Vacation";
                    _emailService.SendEmail(email, $"¡Hola {vacaciones.EmpleadoID}! Sus vacaciones inician: {vacaciones.FechaInicio} y finalizan: {vacaciones.FechaFin}", subject, type);

                    return RedirectToAction(nameof(Index)); // Redirecciona al Index después de crear exitosamente
                }
                // Si el modelo no es válido, vuelve a mostrar la vista Create con los errores de validación
                return View(vacaciones);
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = $"Error: {ex.Message}";
                return View(vacaciones); // Si hay una excepción, vuelve a mostrar la vista Create con un mensaje de error
            }
        }


        // GET: VacacionesController/Edit/5
        public ActionResult Edit(int id)
        {
            var vacaciones = _vacacionesRepository.GetById(id);

            if (vacaciones == null)
            {
                return NotFound();
            }

			string email = "empleado@empleado.com";
			string subject = vacaciones.Tipo;
			string type = "Vacation";
			_emailService.SendEmail(email, $"¡Hola {vacaciones.EmpleadoID}! Sus vacaciones inician: {vacaciones.FechaInicio} y finalizan: {vacaciones.FechaFin}", subject, type);

			return View(vacaciones);
        }

        // POST: VacacionesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(VacacionesModel vacaciones)
        {
            try
            {
                _vacacionesRepository.Edit(vacaciones);

                TempData["editEmpleado"] = "Se editó el ";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(vacaciones);
            }
        }

        // GET: VacacionesController/Delete/5
        public ActionResult Delete(int id)
        {
            var vacaciones = _vacacionesRepository.GetById(id);

            if (vacaciones == null)
            {
                return NotFound();
            }

            return View(vacaciones);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(VacacionesModel vacaciones)
        {
            try
            {
                _vacacionesRepository.Delete(vacaciones.IDVacaciones);

                TempData["deleteVacaciones"] = "Se eliminaron las vacaciones con éxito";

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["deleteVacaciones"] = ex.Message;

                return View(vacaciones);
            }
        }
    }
}

Marcar Asistencias/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Marcar_Asistencias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Marcar_Asistencias.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/1.13.8/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css" rel="stylesheet">
    <link href="https://cdn.datatables.net/responsive/2.5.0/css/responsive.dataTables.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Marcar_Asistencias</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Catalogo
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Empleados" asp-action="Index">Empleados</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Ausencias" asp-action="Index">Regristro de ausencias</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Horarios" asp-action="Index">Horarios</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Vacaciones" asp-action="Index">Dias Libres</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Comentarios" asp-action="Index">Comentarios / Notas</a>
                                </li>
                            </ul>
                        </li>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Marcar_Asistencias - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>